version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/cloudfunction"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
